
early = {'exact_unigrams': {},
         'exact_bigrams': {'foreign work', 'foreign worker', 'foreign workers',
                           'foreign labor', 'foreign laborer', 'foreign laborers'},
         'p2': {},
         'p3': {},
         'p4': {'jews', 'jewi', 'race', 'born'},
         'p5': {'immig', 'inmig', 'imnig', 'imigr', 'iumig', 'immlg', 'emigr', 'migra', 'alien', 'chine',
                'irish', 'iwish', 'irise', 'ivish', 'itish', 'inish', 'cooly', 'dutch', 'norwe', 'finni',
                'swedi', 'welsh', 'quota', 'idiot', 'zioni', 'racis', 'slavs', 'anglo', 'saxon', 'birth',
                'asiat', 'asian'},
         'p6': {'immnig',
                  'imnmig',
                  'inmmig',
                  'immlig',
                  'imlmig',
                  'ilmmig',
                  'imimig',
                  'imumig',
                  'imamig',
                  'chiine',
                  'chiese',
                  'chinse',
                  'clines',
                  'ciiese',
                  'chinam',
                  'coolie',
                  'celest',
                  'mongol',
                  'japane',
                  'apanes',
                  'german',
                  'gernan',
                  'polish',
                  'danish',
                  'celtic',
                  'ethnic',
                  'slavic',
                  'teuton',
                  'hebrew',
                  'scandi',
                  'sicili',
                  'neapol',
                  'slovak',
                  'bohemi'},
         'p7': {'scottis',
                  'gernman',
                  'germnan',
                  'germlan',
                  'italian',
                  'newcome',
                  'arrival',
                  'belgian',
                  'russian',
                  'undesir',
                  'epilept',
                  'lunatic',
                  'assimil',
                  'melting',
                  'europea',
                  'europei',
                  'etropea',
                  'earopea',
                  'enropea',
                  'uropean',
                  'tongues',
                  'hungari',
                  'orienta'},
         'p8': {'foreigne'},
         'p9': {'naturaliz', 'englishne', 'unassimil', 'citizensh', 'citizensb'},
         'p10': {'nativeborn', 'hyphenated', 'americaniz'},
         'p11': {'unnaturaliz', 'foreignborn', 'foreign-bor', 'native-born'},
         'seven_letter_exclude': {'germany', 'alienat', 'germane', 'gernane', 'polishe', 'quotati', 'idiotic'}
}

mid = {'exact_unigrams': {},
       'exact_bigrams': {'foreign work', 'foreign worker', 'foreign workers',
                         'foreign labor', 'foreign laborer', 'foreign laborers',
                         'foreign born', 'native born',
                         'ellis island',
                         'foreign worker', 'foreign workers',
                         'foreign labor', 'foreign laborers',
                         'guest worker', 'guest workers',
                         'seasonal work', 'seasonal worker', 'seasonal workers',
                         'permanent resident', 'permanent residents', 'permanent residency',
                         'work permit', 'work permits',
                         'day labor', 'day laborer', 'day laborers',
                         'low skilled', 'high skilled'},
       'p2': {},
       'p3': {},
       'p4': {'jewi', 'visa', 'asyl'},
       'p5': {'immig', 'emigr', 'migra', 'alien', 'chine',
              'irish', 'quota', 'cuban', 'inmig', 'passp',
              'asiat', 'asian', 'undoc', 'i.n.s'},
       'p6': {'chinam', 'ethnic', 'border', 'deport'},
       'p7': {'newcome', 'undesir',
              'orienta', 'customs', 'refugee', 'mexican',
              'bracero', 'origins', 'wetback', 'illegal',
              'unlawfu', 'smuggle'},
       'p8': {'nonrefug', 'foreigne', 'arrivals', 'nonimmig',
              'detainee', 'nonquota', 'subquota', 'resettle',
              'filipino', 'arrivals'},
       'p9': {'naturaliz', 'unassimil', 'nonreside', 'nationali',
              'detention', 'nationals', 'citizensh'},
       'p10': {'nativeborn', 'americaniz', 'farmworker', 'declarants'},
       'p11': {'unnaturaliz', 'foreignborn', 'foreign-bor', 'native-born', 'nationalori',
               'commemorati', 'americanbor'},
       'seven_letter_exclude': {'alienat', 'quotati', 'borderl'}
}

modern = {'exact_unigrams': {'ins'},
          'exact_bigrams': {'foreign born',
                             'native born',
                             'ellis island',
                             'foreign worker', 'foreign workers',
                             'foreign labor', 'foreign laborers',
                             'guest worker', 'guest workers',
                             'permanent resident', 'permanent residents', 'permanent residency',
                             'work permit', 'work permits',
                             'day labor', 'day laborer', 'day laborers',
                             'seasonal worker', 'seasonal workers',
                             'low skilled', 'high skilled',
                             'dream act'
                             },
          'p2': {'j1', 'jl'},
          'p3': {'h1b', 'hlb', 'i94', 'h2b', 'dhs'},
          'p4': {'visa', 'asyl', 'daca'},
          'p5': {'undoc', 'migra', 'alien', 'quota', 'cuban', 'irish', 'emigr', 'i.n.s', 'd.h.s',
                  'imnig', 'inmig', 'immlg', 'carib', 'uscis', 'asian'},
          'p6': {'border', 'deport', 'hispan', 'amnest', 'coolie', 'mongol'},
          'p7': {'customs', 'everify', 'haitian', 'refugee', 'refuges', 'italian', 'mexican', 'bracero'},
          'p8': {'nonrefug', 'foreigne', 'newcomer', 'arrivals', 'dreamers', 'jamaican', 'multicul',
                  'detainee', 'nonquota', 'subquota', 'resettle', 'honduran', 'nonimmig', 'illegals', 'filipino'},
          'p9': {'naturaliz', 'citizensh', 'citizensb', 'nonreside',
                 'detention', 'illegally', 'colombian', 'nonhispan'},
          'p10': {'nativeborn', 'americaniz', 'farmworker', 'lowskilled',
                 'salvadoran', 'guatemalan', 'nicaraguan', 'dominicans'},
          'p11': {'unnaturaliz', 'foreignborn', 'highskilled', 'salvadorian'},
          'seven_letter_exclude': {'alienat', 'quotati', 'borderl', 'caribou'}
}