frame_words = {'Victims': {'languish (v)', 'sanctuary (n)', 'relief (n)', 'feed (v)',
                           'survivor (n)', 'compassion (n)', 'hope (v)', 'suffering (n)',
                           'help (v)', 'acceptance (n)', 'persecute (v)', 'aid (v)',
                           'deserve (v)', 'amnesty (n)', 'hopeful (j)','reward (v)',
                           'helpless (j)', 'refugee (n)', 'assist (v)', 'struggle (n)',
                           'unfortunate (j)', 'flee (v)', 'aid (n)', 'victim (n)',
                           'rescue (v)', 'afflict (v)', 'battered (j)', 'penniless (j)',
                           'prejudice (n)', 'asylum (n)', 'orphan (n)', 'desperate (j)',
                           'plight (n)', 'exploit (v)', 'humanitarian (j)',
                           'refuge (n)', 'welcome (v)', 'tragedy (n)',
                           'shelter (v)', 'impoverished (j)', 'assisted (j)',
                           'persecution (n)', 'assistance (n)', 'escape (v)'},
               'Contribution': {'veteran (n)', 'attract (v)', 'contribute (v)',
                                'ability (n)', 'industrious (j)', 'friendly (j)',
                                'hardworking (j)', 'selfsufficiency (n)', 'worthy (j)',
                                'genuine (j)', 'sturdy (j)', 'patent (n)',
                                'enlist (v)', 'build (v)', 'qualified (j)',
                                'loyal (j)', 'lawabide (v)', 'desirable (j)',
                                'contribution (n)', 'highskilled (j)', 'gain (v)',
                                'enrich (v)', 'hero (n)'},
               'Family': {'son (n)', 'kid (n)', 'girl (n)', 'grandchild (n)',
                          'marriage (n)', 'descendent (n)', 'husband (n)',
                          'granddaughter (n)', 'marry (v)', 'generation (n)',
                          'child (n)', 'ancestor (n)', 'wife (n)', 'neighbor (n)',
                          'orphan (n)', 'family (n)', 'familybased (j)', 'household (n)',
                          'boy (n)', 'spouse (n)', 'relative (n)', 'parent (n)',
                          'grandson (n)', 'neighborhood (n)', 'relative (j)',
                          'familysponsored (j)', 'grandparent (n)', 'descendant (n)',
                          'daughter (n)'},
               'Culture': {'diverse (j)', 'foreigner (n)', 'integration (n)',
                           'heritage (n)', 'society (n)', 'race (n)',
                           'citizenship (v)', 'americanization (n)', 'integrate (v)',
                           'tradition (n)', 'ethnic (j)', 'christian (j)', 'flag (n)',
                           'culture (n)', 'diversity (n)', 'nation (n)', 'background (n)',
                           'assimilate (v)', 'language (n)', 'assimilation (n)'},
               'Deficient': {'objectionable (j)', 'slacker (n)', 'drunk (j)',
                             'aidsinfected (j)', 'unskilled (j)', 'undesirable (j)',
                             'diseased (j)', 'insane (j)', 'unfit (j)', 'insane (n)',
                             'cheap (j)', 'illiterate (j)', 'ignorant (j)', 'illiteracy (n)'},
               'Crime': {'steal (v)', 'bootlegger (n)', 'absconder (n)',
                         'imprison (v)', 'incarceration (n)', 'illegal (j)', 'convict (v)',
                         'inmate (n)', 'fugitive (j)', 'terrorist (n)', 'apprehend (v)',
                         'imprisonment (n)', 'arrest (v)', 'criminal (j)',
                         'prosecution (n)', 'smuggler (n)', 'noncriminal (j)', 'felon (n)',
                         'detain (v)', 'jail (v)', 'arrest (n)', 'detainee (n)',
                         'smuggling (n)', 'prosecute (v)', 'violent (j)', 'terrorist (j)',
                         'parole (n)', 'gang (n)', 'incarcerate (v)', 'unlawful (j)',
                         'smuggle (v)', 'offense (n)', 'parole (v)', 'criminalize (v)',
                         'criminal (n)', 'capture (v)'},
               'Threat': {'infect (v)', 'aidsinfected (j)', 'combatant (n)',
                          'enemy (n)', 'attack (v)', 'invasion (n)', 'danger (n)',
                          'diseased (j)', 'terrorist (n)', 'attack (n)', 'blame (v)',
                          'dangerous (j)', 'overrun (n)', 'threaten (v)', 'problem (n)',
                          'violent (j)', 'terrorist (j)', 'gang (n)', 'anarchist (n)',
                          'belligerent (n)', 'horde (n)', 'apprehension (n)'},
               'Economic': {'sale (n)', 'fund (n)', 'agricultural (j)', 'compete (v)',
                            'cent (n)', 'reimbursement (n)', 'funding (n)',
                            'bank (n)', 'ownership (n)', 'purchase (v)', 'finance (v)',
                            'buy (v)', 'specie (n)', 'property (n)', 'taxpayer (n)',
                            'owner (n)', 'coin (v)', 'allocation (n)', 'cost (v)',
                            'economic (j)', 'cash (n)', 'corporation (n)', 'tax (n)',
                            'taxpaye (v)', 'competition (n)', 'pay (v)', 'investor (n)',
                            'workforce (n)', 'tax (v)', 'budget (n)'},
               'Labor': {'agricultural (j)', 'compete (v)', 'unskilled (j)',
                         'employer (n)', 'hiring (n)', 'miner (n)', 'employmentbased (j)',
                         'nurse (n)', 'hire (v)', 'crewman (n)', 'employment (n)',
                         'farmworker (n)', 'tailor (n)', 'employee (n)', 'worker (n)',
                         'competition (n)', 'workforce (n)', 'laborer (n)', 'employ (v)'},
               'Legality': {'legitimate (j)', 'citizenship (n)', 'hearing (n)',
                            'status (n)', 'undocumented (j)', 'law (n)', 'legal (j)',
                            'license (n)', 'legalized (j)', 'lawful (j)',
                            'verification (n)', 'eligible (j)', 'illegal (j)',
                            'permanent (j)', 'citizenship (v)', 'naturalize (v)',
                            'registration (n)', 'naturalization (n)', 'amnesty (n)',
                            'inadmissible (j)', 'applicant (n)', 'exemption (n)',
                            'visa (n)', 'ineligible (j)', 'qualify (v)', 'sponsor (v)',
                            'registered (j)', 'prosecute (v)', 'identification (n)',
                            'authorize (v)', 'unnaturalized (j)',
                            'authorization (n)', 'sponsor (n)',
                            'unauthorized (j)', 'overstay (v)',
                            'unlawful (j)', 'eligibility (n)', 'legalize (v)',
                            'adjudication (n)', 'familysponsored (j)', 'legalization (n)',
                            'application (n)'},
               'Quantity': {'estimated (j)', 'much (j)', 'bunch (n)', 'thousand (n)',
                            'most (j)', 'percentage (n)', 'many (j)', 'million (n)',
                            'entire (j)', 'count (v)', 'number (v)', 'mass (n)',
                            'crowd (n)', 'additional (j)', 'twothird (n)', 'counting (n)',
                            'count (n)', 'total (n)', 'total (j)', 'flock (v)',
                            'increase (v)', 'statistic (n)', 'boatload (n)',
                            'more (j)', 'shipload (n)', 'estimate (v)', 'cap (n)',
                            'majority (n)', 'masse (n)', 'bulk (n)', 'fraction (n)',
                            'sum (n)', 'estimate (n)', 'number (n)', 'proportion (n)',
                            'horde (n)'},
               'Flood/Tide': {'stream (v)', 'flow (n)', 'absorb (v)', 'flood (n)',
                              'wave (n)', 'spill (v)', 'inflow (n)', 'trickle (n)',
                              'influx (n)', 'surge (n)', 'fill (v)', 'pour (v)', 'stream (n)',
                              'absorption (n)', 'outflow (n)', 'flow (v)', 'flood (v)',
                              'tide (n)', 'drain (v)'},
               'Exclusion': {'reject (v)', 'limitation (n)', 'requirement (n)',
                             'deportable (j)', 'removable (j)', 'deport (v)', 'shut (v)',
                             'stop (v)', 'prohibition (n)', 'interdict (v)', 'screen (v)',
                             'debar (v)', 'restrict (v)', 'deported (j)', 'bar (v)',
                             'quota (n)', 'expel (v)', 'inadmissible (j)',
                             'deportation (n)', 'deter (v)', 'vet (v)', 'exclude (v)',
                             'allow (v)', 'interdiction (n)', 'ban (v)', 'detain (v)',
                             'removal (n)', 'ceiling (n)', 'forbid (v)', 'exclusion (n)',
                             'deny (v)', 'excludable (j)', 'cap (n)', 'vetting (n)',
                             'bar (n)', 'prevent (v)', 'expulsion (n)', 'inspect (v)',
                             'prohibit (v)', 'unauthorized (j)', 'overstay (v)',
                             'screening (n)', 'limit (n)', 'admissibility (n)',
                             'eligibility (n)', 'limit (v)', 'ban (n)', 'restriction (n)',
                             'criterion (n)'},
               'Migration': {'enter (v)', 'destination (n)', 'flight (n)', 'ship (v)',
                             'route (n)', 'seaman (n)', 'relocate (v)', 'passenger (n)',
                             'incoming (j)', 'leave (v)', 'relocation (n)', 'exodus (n)',
                             'arrival (n)', 'land (v)', 'convoy (n)', 'depart (v)',
                             'settle (v)', 'landing (n)', 'move (v)', 'port (n)',
                             'travel (v)', 'resettle (v)', 'arrive (v)', 'displacement (n)',
                             'settlement (n)', 'cross (v)', 'station (n)', 'resettling (n)',
                             'return (v)', 'migration (n)', 'movement (n)', 'coming (n)',
                             'reenter (v)', 'departure (n)', 'entrance (n)', 'depot (n)',
                             'boatload (n)', 'shipload (n)', 'emigrate (v)',
                             'resettlement (n)', 'migrate (v)', 'come (v)',
                             'return (n)', 'transport (v)', 'passage (n)',
                             'immigrate (v)', 'entry (n)'},
               'Background': {'immigration (n)'}
               }


def get_tagged_frame_terms():
    return frame_words


# replacements to make to account for the different preprocessing of Gentzkow and USCR (hyphenation, etc.)
frame_queries = {'self sufficiency': 'selfsufficiency',
                      'law abide': 'lawabide',
                      'high skilled': 'highskilled',
                      'family based': 'familybased',
                      'family sponsored': 'familysponsored',
                      'aids infected': 'aidsinfected',
                      'employment based': 'employmentbased',
                      'farm worker': 'farmworker',
                      'two third': 'twothird',
                      }

frame_replacements = {'self (n) sufficiency (n)': 'selfsufficiency (n)',
                      'law (n) abide (v)': 'lawabide (v)',
                      'high (j) skilled (j)': 'highskilled (j)',
                      'family (n) based (n)': 'familybased (j)',
                      'family (n) sponsored (j)': 'familysponsored ()',
                      'aids (n) infected (j)': 'aidsinfected (j)',
                      'employment (n) based (n)': 'employmentbased (j)',
                      'farm (n) worker (n)': 'farmworker (n)',
                      'farm (v) worker (n)': 'farmworker (n)',
                      'two (c) third (n)': 'twothird (n)',
                      }


def get_frame_replacements():
    return frame_replacements
